---
# tasks file for addsmbshare
- name: Install the utilites for cifs
  apt:
    name: "{{ addsmbshare_listprograms }}"
    update_cache: yes
    force: yes
  become: yes

- name: Copy credential file
  copy: 
    src: "{{ addsmbshare_credentialsfile }}"
    dest: /root/
  become: yes

- name: Create the folder
  file:
    path: "{{ item[0] }}"
    state: directory
    mode: '0777'
  with_items:
    - "{{ addsmbshare_sources }}"
  become: yes
  
- name: Add mount
  mount:
    path: "{{ item[0] }}"
    src: "{{ item[1] }}"
    opts: "credentials=/root/{{ addsmbshare_credentialsfile }},iocharset=utf8,file_mode=0777,dir_mode=0777"
    fstype: cifs
    state: mounted
  with_items:
    - "{{ addsmbshare_sources }}"
  become: yes
