---
# vars file for enableopenvpn
enableopenvpn_src: /home/{{ ansible_user }}/openvpn/*

enableopenvpn_dest: /etc/openvpn/

enableopenvpn_ovpn: /etc/openvpn/{{ ansible_hostname }}.ovpn

enableopenvpn_conf: /etc/openvpn/client/{{ ansible_hostname }}.conf

enableopenvpn_service: openvpn-client@{{ ansible_hostname }}

enableopenvpn_routes:
#- ['172.17.150.0/24', '192.168.5.254']
#- ['192.168.120.0/18', '192.168.5.254']
- ['172.17.150.0/24', '192.168.108.254']
- ['192.168.120.0/18', '192.168.108.254']
- ['192.168.5.0/24', '192.168.108.254']
- ['192.168.0.0/24', '192.168.108.254']
