---
# tasks file for rename
- name: Remove old desktop file
  file: 
    path: "/home/{{ ansible_user }}/Рабочий стол/{{ item }}"
    state: absent
  with_items:
    - "{{ rename_removefiles }}"
  become: yes

- name: Add desktop file
  template: 
    src: "home/user/Desktop/{{ item }}.j2"
    dest: "/home/{{ ansible_user }}/Рабочий стол/{{ item }}"
    mode: 0750
  with_items:
    - "{{ rename_files }}"

#- name: Remove old desktop file
#  file:
#    path: "/home/{{ ansible_user }}/Рабочий стол/{{ item }}"
#    state: absent
#  with_items:
#    - "{{ rename_removefiles }}"
