---
- name: Create directoryes
  file: 
    path: /home/{{ ansible_user }}/install/{{ item[1] }}
    state: directory
  with_items:
  - "{{ installcryptopro_listpackages }}"

- name: Unpack the archive for the CryptoPro
  unarchive:
    src: "{{ item[0] }}"
    dest: /home/{{ ansible_user }}/install/{{ item[1] }}
  with_items:
    - "{{ installcryptopro_listpackages }}"

- name: Install CpyptoPro
  shell: sh install.sh
  args:
    chdir: /home/{{ ansible_user }}/install/cryptopro/linux-amd64_deb/
  become: yes

- name: Create a symbolic link
  file:
    src: /opt/cprocsp/bin/amd64/{{ item }}
    dest: /bin/{{ item }}
    state: link
  with_items:
    - "{{ installcryptopro_utils }}"
  become: yes

- name: Install plugin for Firefox
  apt:
    deb: "/home/{{ ansible_user }}/install/extention/cades_linux_amd64/{{ item }}"
    force: yes
  with_items:
    - "{{ installcryptopro_debpackage }}"
  become: yes

- name: Install packages for PyTOKEH
  apt:
    name: "{{ item }}"
    force: yes
  with_items:
    - "{{ installcryptopro_forpytoken }}"
  become: yes

- name: Install PyTOKEH
  apt:
    deb: "/home/{{ ansible_user }}/install/cryptopro/linux-amd64_deb/{{ item }}"
    force: yes
  with_items:
    - "{{ installcryptopro_pytoken }}"
  become: yes

- name: Remove install folder
  file: 
    path: /home/{{ ansible_user }}/install 
    state: absent
  become: yes
