---
# tasks file for nginxcentosinstall
- name: Add repository
  yum_repository:
    name: "{{ nginxcentosinstall_reponame }}"
    description: "{{ nginxcentosinstall_reponame }} YUM repo"
    baseurl: "{{ nginxcentosinstall_repobaseurl }}"
  with_items:
   - { name: "nginx" }
   - { baseurl: "http://nginx.org/packages/centos/$releasever/$basearch/" }
  become: yes

- name: Add repository
  yum_repository:
    name: nginx
    description: nginx YUM repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/

- name: Install packages for Centos
  yum:
   name: "{{ nginxcentosinstall_packages }}"
   state: present
  become: yes
  when: ansible_distribution == 'Centos'



# tasks file for openvpn_client
- name: Install openvpn client
  apt:
   pkg: "{{ item.pkg }}"
   state: present
  with_items:
    - { pkg: "openvpn=2.3.10-1ubuntu2" }
  become: yes
