---
# tasks file for 1C-install_think-client
- name: Copy file.role1 to file
  copy: src=1c-enterprise83-thin-client_8.3.10-2639_amd64.deb dest=/home/admingkb7/install/

#- name: Install 1C client
#  apt:
#   deb: /home/admingkb7/install/1c-enterprise83-thin-client_8.3.10-2639_amd64.deb
#   dpkg_options: 'extract'
#   #dpkg_options: 'unpack'
#   force: 'true'
#  become: yes
- name: Add automation file
  template: src="home/admingkb7/install/automation.sh.j2" dest="/home/admingkb7/install/automation.sh"
#  template: src="{{ item }}.j2" dest="/{{ item }}"
#  with_items:
#   - "home/admingkb7/install/automation.sh"

- name: Execute the command in remote shell; stdout goes to the specified file on the remote.
  shell: sh automation.sh
  args:
    chdir: /home/admingkb7/install/

#- name: Configure openvpn client
#  template: src="{{ item }}.j2" dest="/{{ item }}"
#  with_items:
#   - "etc/openvpn/client.conf"
#  become: yes
#  notify:
#   - Start openvpn client
#   - Enable service openvpn client
