---
# handlers file for openvpn_client
 - name: Start openvpn client
   systemd:
    state: started
    name: openvpn@client.service
   become: yes
 
 - name: Enable service openvpn client
   systemd:
    name: openvpn@client.service
    enabled: yes
    masked: no
   become: yes
